# Generated by Django 2.2 on 2019-04-06 08:58

from django.db import migrations
from decimal import Decimal
from django.conf import settings


def preload_data(apps, schema_editor):
    Item = apps.get_model('api', 'Item')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    users = (
        {'username': 'testuser', 'password': 'test123'},
        {'username': 'devuser', 'password': 'dev123'},
    )
    for user in users:
        User.objects.create(
            username=user.get('username'),
            password=user.get('password'),
        )

    items = (
        {'id': 1, 'price': Decimal('28.57'), 'discounted': False},
        {'id': 2, 'price': Decimal('15.36'), 'discounted': False},
        {'id': 3, 'price': Decimal('118.53'), 'discounted': True},
        {'id': 4, 'price': Decimal('58.75'), 'discounted': False},
        {'id': 5, 'price': Decimal('8.20'), 'discounted': False},
        {'id': 6, 'price': Decimal('725.00'), 'discounted': True},
    )
    for item in items:
        Item.objects.create(
            id=item.get('id'),
            price=item.get('price'),
            discounted=item.get('discounted'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(preload_data),
    ]
