# Generated by Django 2.2 on 2019-04-06 18:46
from decimal import Decimal

from django.db import migrations


def preload_voucher_data(apps, schema_editor):
    Voucher = apps.get_model('api', 'Voucher')

    vouchers = (
        {'code': 'abct123', 'discounted_rate': Decimal('0.20')},
        {'code': 'dreq563', 'discounted_rate': Decimal('0.10')},
        {'code': 'ewrt200', 'discounted_rate': Decimal('0.05')},
        {'code': 'preq700', 'discounted_rate': Decimal('0.30')},

    )
    for voucher in vouchers:
        Voucher.objects.create(
            code=voucher.get('code'),
            discounted_rate=voucher.get('discounted_rate'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190406_1823'),
    ]

    operations = [
        migrations.RunPython(preload_voucher_data),
    ]
