# Generated by Django 2.2 on 2019-04-07 17:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190406_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolley',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
    ]
