# Generated by Django 2.2 on 2019-04-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190407_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
